# Generated by Django 5.1.6 on 2025-02-16 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(choices=[('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], max_length=10)),
                ('community_string', models.CharField(blank=True, help_text='Required for SNMPv1 and SNMPv2c', max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text='Required for SNMPv3', max_length=100, null=True)),
                ('auth_protocol', models.CharField(blank=True, choices=[('MD5', 'MD5'), ('SHA', 'SHA')], help_text='Authentication protocol for SNMPv3', max_length=10, null=True)),
                ('auth_password', models.CharField(blank=True, help_text='Authentication password for SNMPv3', max_length=100, null=True)),
                ('priv_protocol', models.CharField(blank=True, choices=[('DES', 'DES'), ('AES', 'AES')], help_text='Privacy protocol for SNMPv3', max_length=10, null=True)),
                ('priv_password', models.CharField(blank=True, help_text='Privacy password for SNMPv3', max_length=100, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='community_string',
        ),
        migrations.RemoveField(
            model_name='device',
            name='snmp_version',
        ),
        migrations.AddField(
            model_name='device',
            name='probe_type',
            field=models.CharField(choices=[('snmp', 'SNMP'), ('icmp', 'ICMP (Ping)')], default='icmp', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_credential',
            field=models.ForeignKey(blank=True, help_text='Required only if probe type is SNMP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nms.snmpcredential'),
        ),
    ]
