# Generated by Django 5.1.6 on 2025-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0003_snmpcredential_remove_device_community_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Device MAC address (format: XX:XX:XX:XX:XX:XX)', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number (optional)', max_length=100, null=True),
        ),
    ]
